### ISSUE TITLE
False positive when class uses Traits - reproduce it

### ISSUE THREAD

**Issue by matks** [PrestaShop/phpstan-prestashop#20]
Steps

- [x] Introduce acceptance tests https://github.com/PrestaShop/phpstan-prestashop/pull/22/
- [x] Use extension inside acceptance tests https://github.com/PrestaShop/phpstan-prestashop/pull/23
- [x] Reproduce this bug with acceptance tests

https://github.com/PrestaShop/PrestaShop/pull/20370/checks?check_run_id=2076975662

```
  Line   Core/Grid/Definition/Factory/BulkDeleteActionTrait.php (in context of class PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ZoneGridDefinitionFactory)  
 ----
  43     Function buildBulkDeleteAction should declare return type.                                                                                                 
 ```
 
 When class `A` uses trait `B`, if B class methods do not comply with PHPStan rules, errors are reported in the analyzis of class A, not trait B.

**Comment by matks** [comment]
Cant reproduce 😭 https://github.com/PrestaShop/phpstan-prestashop/pull/21

**Comment by PierreRambaud** [comment]
Your description seems outdated, I'm not able to see what was the problem, and which kind of code was used to reproduce the issue :(

**Comment by matks** [comment]
@PierreRambaud Class ZoneGridDefinitionFactory was using trait BulkDeleteActionTrait.

Class method `BulkDeleteActionTrait:: buildBulkDeleteAction()` does not have return type, and return type cannot be added as this would be a BC break.

However **what is wrong** is that this "need return type!" report is given by phpstan when exploring class ZoneGridDefinitionFactory, not trait BulkDeleteActionTrait. The class is reported faulty although the issue comes from the trait it relies on.

Looks like I cannot reproduce it using PHPStan TestCase for PHPUnit. It might only appear when scanning a full app, not isolated files.

**Comment by matks** [comment]
According to @PierreRambaud this bug cannot be catched by a unit tests because it indeeds finds a bug of trait A when analyzing class B and that is outside (as far as we know) of PHPStan TestCase for PHPUnit.

So I need **acceptance tests** for phpstan-prestashop that will scan a full application.

Roadmap to have acceptance tests for this bug
- [x] Introduce acceptance tests https://github.com/PrestaShop/phpstan-prestashop/pull/22/
- [x] Use extension inside acceptance tests https://github.com/PrestaShop/phpstan-prestashop/pull/23
- [x] Reproduce this bug with acceptance tests

**Comment by matks** [comment]
@ondrejmirtes I know you like to monitor what's going on with PHPStan extension 😄  you might be interested by this topic ("How to test your PHPStan extension with real phpstan PHAR a.k.a acceptance tests")

**Comment by ondrejmirtes** [comment]
> and return type cannot be added as this would be a BC break.

You can add it just in the PHPDoc as `@return`. See all the possibilities: https://phpstan.org/writing-php-code/phpdocs-basics + https://phpstan.org/writing-php-code/phpdoc-types

> So I need acceptance tests for phpstan-prestashop that will scan a full application.

You can run PHPStan as normally on a full application in your CI and have the build failed in case it finds some errors.

**Comment by matks** [comment]
> You can run PHPStan as normally on a full application in your CI and have the build failed in case it finds some errors.

No, I _want_ PHPStan to fail in some cases 😄  (because the failure cases are what my extension adds) and I want to assert the content of these failures.

Right now what I do in https://github.com/PrestaShop/phpstan-prestashop/pull/22 is
- run phpstan againt a sample app
- export errors in JSON
- validate JSON content by a php script, to assert what it contains is expected

I will check later if one of the official PHPStan extensions has a similar need and testing usecase

**Comment by ondrejmirtes** [comment]
The thing you're doing in https://github.com/PrestaShop/phpstan-prestashop/pull/22 is probably the best idea, PHPStan itself does something similar with integration tests on rule levels...
